project:
  type: website
  output-dir: docs

website:
  title: "Fox Kloske"
  navbar:
    left:
      - text: "Home"     
        href: index.qmd
      - text: "Data Viz"
        menu:
          - text: "United States Spending on Children"
            href: tidy1.qmd
          - text: "Transit-Infrastructure Costs"
            href: tidy2.qmd

format:
  html:
    theme:
      - cosmo
     # - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

