project:
  type: website
  output-dir: docs

website:
  title: "Fox Kloske"
  favicon: media/fox.png
  navbar:
    pinned: true
    right:
      - text: "Data Exercises"
        menu:
          - text: "English Academic Achievement"
            href: SimulationStudy.qmd
          - text: "Stanford Open Policing"
            href: SQLexercise.qmd
          - text: "New York City Taxi Cabs"
            href: ethics.qmd
          - text: "Central Park Squirrels"
            href: txtanalysis.qmd
          - text: "United States Spending on Children"
            href: tidy1.qmd
          - text: "Transit-Infrastructure Costs"
            href: tidy2.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual